# Generated by Django 5.1.4 on 2024-12-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_bins', '0002_alter_notification_bin_delete_route_delete_wastebin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
