# Generated by Django 5.2.3 on 2025-09-17 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastebin',
            name='fill_level',
            field=models.IntegerField(default=0, help_text='Fill percentage (0-100%)'),
        ),
        migrations.AlterField(
            model_name='wastebin',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
